### PR TITLE
Theorized fix for theorized bug #390 option 1 - taking a Read lock 

### PR DESCRIPTION
**Pull request by TimLovellSmith**
while calling Activator.CreateInstance.

Don't accept this unless it works! I haven't figured out how to test this yet. 😊

### CODE REVIEW

**Comment by stakx** [comment]
May I ask why a PR for this? You should be able to test locally; a PR won't really do you much good at this stage.

>  I haven't figured out how to test this yet. 😊

You'll need the following prerequisites:

* a computer with several physical cores
* Visual Studio JIT Debugging should be enabled / installed

Then proceed roughly as follows:

1. Clone e.g. [BrunoJuchli/Core](https://github.com/BrunoJuchli/Core) and check out the `193` branch.
2. Make your changes to DynamicProxy in the `src/Castle.Core` project.
3. Compile and publish the `src/NetCoreRepro` project to `src\NetCoreRepro\bin\Debug\netcoreapp2.1\win10-x64`.
4. Open several command line prompts (say, at least 4) and run `_193.bat` in each of them. This will execute the published project in a loop.
5. Let it run up to several hours until an error happens.

**Comment by TimLovellSmith** [comment]
So far:
I did a very short run with the added write lock (not the read lock of this PR) and couldn't repro any crash yet.
I did another very short run with no locking and couldn't repro any of the exceptions from #193 per se, but did run into one app crash:

```
Application: NetCoreRepro.exe CoreCLR Version: 4.6.26515.7 Description: The  process was terminated due to an internal error in the .NET Runtime at IP  00007FFEDB9F9B04 (00007FFEDB650000) with exit code 80131506
```

According to StackOverflow answers this indicates an ExecutionEngineException. Quote

>The generic cause is corruption of the state of the garbage collected heap. Which in turn is invariably caused by unmanaged code

[or]

>bugs in concurrent garbage collection...

**Comment by fir3pho3nixx** [comment]
@TimLovellSmith 

A long time ago when I used to muck around with methods like [ICorProfilerInfo::GetILFunctionBody](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilerinfo-getilfunctionbody-method) and [ICorProfilerInfo::SetILFunctionBody](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilerinfo-setilfunctionbody-method) I used to get this exception all the time. It was almost always because I cocked up the IL.

**Comment by stakx** [comment]
@TimLovellSmith - I can confirm that putting a read lock around `Activator.CreateInstance` makes the error either disappear, or a lot less likely to happen&mdash;see https://github.com/castleproject/Core/issues/193#issuecomment-400206187.

However, that doesn't mean that putting a lock around `Activator.CreateInstance` is definitely the right thing to do. The error might just become a lot less likely. I stopped my test run after 8 hours (the error usually occurs after approx. 2 1/2 hours on my machine), but it might be necessary to keep the test running for several days (as in e.g. https://github.com/castleproject/Core/issues/193#issuecomment-399839323).

I suggest we keep this PR open for now, until at least next week, when we'll have test results from another test run by @BrunoJuchli.

**Comment by TimLovellSmith** [comment]
Related to https://github.com/castleproject/Core/issues/193#issuecomment-400496224 maybe it is type instantiation, whether via 'new' or 'CreateInstance' which causes all the problems, and so if we just add one more Read lock around newing up the invocation objects, all bugs will be solved!

**Comment by stakx** [comment]
@TimLovellSmith - no. If type instantiation is not thread-safe, then Microsoft needs to fix the runtime.

**Comment by TimLovellSmith** [comment]
@stakx Well I don't disagree, but it seemed like a pretty fun experiment!

**Comment by TimLovellSmith** [comment]
@stakx @BrunoJuchli Well, actually other reasons I mentioned it were 
- it seems to be a good unifying theory behind why we get BadImageFormatException during method invocations
- it might have something to do with why we are having trouble reproing the issue without DynamicProxy, but I am still not sure exactly what.

**Comment by BrunoJuchli** [comment]
@TimLovellSmith 
I agree that if putting a read lock around all instantiations makes the issue vanish it's an indicator that the framework is not performing as it should (concurrency issue with instantiation & emitting).
I'm currently running a test like that.

The general problem with concurrency issues is that generally even a small, seemingly unrelated, changes to the code can have a big impact on the frequency with which errors occur.
So even if it ran for 2 weeks without producing a single error that would not be a guarantee that the change actually fixes the issue.
Here, proof can only work the other way round: If you run the code and it produces an error - it's guaranteed to be buggy.

Still, I'd say if the change means going from an error every 2.5hours to no error in 2 weeks, then I hope this would at least be enough for MS to have a close look.

**Comment by stakx** [comment]
@TimLovellSmith, @BrunoJuchli: This PR is about to go to sleep, so before noone remembers anymore what it was about, I'd like to ask how we should proceed with it.

My personal vote is for closing this PR unmerged. I agree with @BrunoJuchli that (a) it's hard to prove that additional locks actually make the error go away completely vs. just making it much more improbable.; and that (b) the likeliest explanation for the threading issue we've been hunting is a runtime bug. And finally (c), these locks will negatively affect performance of Castle.Core, while providing benefits only in some very marginal scenarios. For these two reasons, I feel we shouldn't do this.

Do you have any objections if I close this PR?

**Comment by stakx** [comment]
Just when I thought you were simply otherwise busy, you're telling me the real reason. 😆 What a crazy hot summer it is, indeed. 🌞

**Comment by jonorossi** [comment]
> My personal vote is for closing this PR unmerged. I agree with @BrunoJuchli that (a) it's hard to prove that additional locks actually make the error go away completely vs. just making it much more improbable; and that (b) the likeliest explanation for the threading issue we've been hunting is a runtime bug (meaning we're not the ones who should "fix" things). And finally (c), these locks will negatively affect performance of DynamicProxy, while providing benefits only in some very marginal scenarios. For these reasons, I feel we shouldn't make this change.
> 
> Do any of you have objections against closing this PR?

I agree, this pull request should be closed unmerged. The performance implications of this change are too severe. Microsoft have already stated that they expect `Activator.CreateInstance` with dynamic types should not have any threading constraints, any required locking on internal runtime structures for mutations should be performed by the runtime.

**Pull request closed without merging**
