### PR TITLE
Feature/492 add project icon to common props

### PR DESCRIPTION
**Pull request by generik0**
Remove PackageIconUrl in favour of the new PackageIcon configuration

#492

### CODE REVIEW

**Comment by generik0** [comment]
Please dont complete. The AppVeyor is not added the "icon" / prakageicon to the nuspec. Maybe old msbuild?

**Comment by stakx** [comment]
@generik0, I noticed too that the icon doesn't appear to work, at least not in VS2017 which I'm still using. I've converted this PR to a "draft" (to prevent accidental merging) until this has been resolved. Hope that's OK with you.

**Comment by generik0** [comment]
@stakx That’s perfect thanks!
How can we move to VS2019?

**Comment by stakx** [comment]
> How can we move to VS2019?

If you're thinking of the CI build, that would be done by changing `appveyor.yml`:

https://github.com/castleproject/Core/blob/0d12f9c12b5f843ac555f7dea22d7fe8194fae03/appveyor.yml#L2

AppVeyor has a list of [available worker images](https://www.appveyor.com/docs/build-environment/#build-worker-images), which includes `Visual Studio 2019`.

Our CI build is currently broken due to a regression in Mono, perhaps it would be best to get that fixed first, and upgrade to the newer Visual Studio 2019 image at the same time.

**Comment by generik0** [comment]
Let me know if I can help with anything :-)

**Comment by stakx** [comment]
@generik0 we've now switched to VS2019's toolchain on our AppVeyor CI Windows build in current `master` (6685222d3db3e855882c3654ace808a8f501d1d8). Do you want to rebase this PR and see if the newer tooling resolves the remaining issue with the missing icon?

**Comment by generik0** [comment]
HI @stakx. Sorry about the delay. Busy with work and family. Haven't had the time I needed for anything else (excuses excuses).. 
Now i have the projecticon and projecticonurl in the props

**Comment by stakx** [comment]
@generik0, thanks for contributing! Btw., no need to apologise for the delay... we've all got our lives aside from (unpaid!) work on open source projects. It's great you came back to finalize this! :-)

**Pull request merged**
