### PR TITLE
Adding doc blocks back

### PR DESCRIPTION
**Pull request by fir3pho3nixx**
Hopefully fixes: https://github.com/castleproject/Core/issues/312

### CODE REVIEW

**Comment by stakx** [comment]
What about the log integration projects' `.csproj` files? Do they not need to have XML documentation enabled?

**Comment by fir3pho3nixx** [comment]
Sorry, did that waaaay to quickly, will add them in.

**Comment by fir3pho3nixx** [comment]
@stakx - All in, thanks for supervising.

**Comment by jonorossi** [comment]
Merged, thanks @fir3pho3nixx.

**Pull request merged**
