### PR TITLE
CI: Update Mono to version 5.16 & un-skip a bunch of tests

### PR DESCRIPTION
**Pull request by stakx**
Just saw in the [Mono 5.16.0 release notes](https://www.mono-project.com/docs/about-mono/releases/5.16.0/) that this version should fix some bugs which caused us to skip some tests.

This PR attempts to unskip some of the tests skipped on Mono by updating the Travis CI build to Mono 5.16.0 and removing specific `[ExcludeOnFramework(Framework.Mono)]` attributes.

(This is work in progress: ~~If it won't work as expected, I'll close the PR until a later time when I'll be trying the same procedure again.~~)

* [X] Unskip as many Mono tests as possible.
* [X] Skip tests that have started failing. (This wasn't exactly planned, obviously.)
* [x] Update [`docs/dynamicproxy-optional-parameter-value-limitations.md`](https://github.com/castleproject/Core/blob/4f741f578746e5a0cbdd87da3e7d2774c877bfe1/docs/dynamicproxy-optional-parameter-value-limitations.md) where necessary
* [X] Submit new bug reports to the Mono project
* [x] ~~Update [Mono guidance in `README.md`](https://github.com/castleproject/Core/blob/4f741f578746e5a0cbdd87da3e7d2774c877bfe1/README.md#mono)~~ (did most of this work in a separate PR already)

### CODE REVIEW

**Comment by stakx** [comment]
@jonorossi, just FYI, there *might* be something wrong with the Travis CI / GitHub integration for this repo. This PR doesn't show the failed Travis CI build ([see build log](https://travis-ci.org/castleproject/Core/builds/440412673)). Perhaps it's just a one-off, perhaps this happens when `.travis.yml` is bad... I'll keep an eye on it.

**Comment by jonorossi** [comment]
> there _might_ be something wrong with the Travis CI / GitHub integration for this repo

Looks like something to do with the fact we are still on the legacy platform (.org not .com, the migration seems to keep getting pushed back) and the changes for moving from GitHub Services to GitHub Apps (the integration service in GitHub said it was inactive, but I can't find a way to use GitHub Apps from .org).

- https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories
- https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps

We can enable other Git repos on travis-ci.com, but this repo is listed with:

> The following repositories cannot be migrated to travis-ci.com at this time because they are currently active on our legacy platform travis-ci.org. This feature will be available shortly. Please [read our docs on open source migration](https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org) to learn more.

That page says we can request for the repo to be moved immediately without build history or build settings.

**Comment by jonorossi** [comment]
@stakx let me know if you think we should just request for the build to be moved over to .com.

It is probably also time we update the guidance about Mono version in the readme.

**Comment by stakx** [comment]
@jonorossi, sorry, I have been a little slow in responding.

> let me know if you think we should just request for the build to be moved over to .com.

I'd say yes &mdash; better to lose build history (which doesn't feel like such a big loss to me) than having no build verification at all.

Not too long ago, you and fir3pho3nixx were discussing whether to standardize builds on AppVeyor (as it now offers Linux machines). That move would mean losing past build logs once again, i.e. that's likely going to happen someday anyway.

**Comment by stakx** [comment]
> It is probably also time we update the guidance about Mono version in the readme.

Oh, I never even really noticed that readme section at all! Good point. I'd suggest we update it with at least the following information:

* The Mono version against which we have built & tested Core. Right now, this is v5.10.1.

* That this repo's issue tracker, as well as (skipped) unit tests, document all known Mono issues that we haven't yet been able to fix.

* That if someone notices anything further that doesn't appear to work as it should, they should first update to *at least* the Mono version we are using for our CI. If the problem persists after that, they should file a new issue.

**Comment by jonorossi** [comment]
> sorry, I have been a little slow in responding.

No problem, I know I've been slow too.

> I'd say yes — better to lose build history (which doesn't feel like such a big loss to me) than having no build verification at all.

Great, I'll get it moved over.

> discussing whether to standardize builds on AppVeyor (as it now offers Linux machines).

Travis now has Windows machines too, so we'll have to compare the two.

> I'd suggest we update it with at least the following information

Do as little or as much of that as you feel like, it all makes sense, we haven't had many people talking about Mono around this project so I wouldn't invest too much time if it becomes a big job to list the current limitations.

**Comment by jonorossi** [comment]
@stakx if you modify (e.g. rebase) this pull request it should now build on Travis. I've got master building and reporting from the new .com platform. I've updated the link to the Linux build in the readme.

**Comment by stakx** [comment]
Here's a short summary of what this PR does so far:

|  | # in `master` | # in this PR | change |
| --- | --: | --: | --: |
| **Test Count:** | 1751 | 1751 |  |
| **Passed:** | 1632 | 1668 | +36 |
| **Failed:** | 0 | 0 |  |
| **Warnings:** | 0 | 0 |  |
| **Inconclusive:** | 60 | 30 | -30 |
| **Skipped:** | 59 | 53 | -6 |

These numbers include the approx. 30 tests that are now newly skipped or inconclusive due to #414.

Here's what remains to be done before merging:

* [ ] Update [`docs/dynamicproxy-optional-parameter-value-limitations.md`](https://github.com/castleproject/Core/blob/4f741f578746e5a0cbdd87da3e7d2774c877bfe1/docs/dynamicproxy-optional-parameter-value-limitations.md) where necessary
* [ ] Update [Mono guidance in `README.md`](https://github.com/castleproject/Core/blob/4f741f578746e5a0cbdd87da3e7d2774c877bfe1/README.md#mono)

**Comment by stakx** [comment]
This is ready.

Two new issues have been submitted to the Mono project (see https://github.com/mono/mono/issues/11302 and https://github.com/mono/mono/issues/11303) and mentioned in our source code for future tracking.

**Comment by stakx** [comment]
These Mono bugs at least are still fixable. We're getting there! But with some of the CLR reflection bugs (I'm thinking of those related to custom modifiers) we've got to a point where it seems unlikely they will be fixed at all, simply because Reflection has some fundamental design flaws in its API that are very hard to change. If we wanted to avoid these bugs, it might actually be necessary to use something more low-level & precise, say, Mono.Cecil or System.Reflection.Metadata. But that's perhaps a topic for another day (albeit a very interesting one!).

**Comment by stakx** [comment]
These Mono bugs at least are still fixable. We're getting there! But with some of the CLR reflection bugs (I'm thinking of those related to custom modifiers) we've got to a point where it seems unlikely they will be fixed at all, simply because Reflection has some fundamental design flaws in its API that are very hard to change. If we wanted to avoid these bugs, it might actually be necessary to use something more low-level & precise, say, Mono.Cecil or System.Reflection.Metadata. But that's perhaps a topic for another day (albeit a very interesting one!).

**Pull request merged**
