### PR TITLE
Remove Silverlight 4.0 support

### PR DESCRIPTION
**Pull request by jamesathey**
Remove support for Silverlight 4.0 from the solutions, projects, build scripts, and nuspec files.

Removing the Silverlight 4.0 build configurations from the project files stops Visual Studio 2013 from complaining that the projects need to be upgraded. If you actually let VS "upgrade" the projects, it makes many breaking changes to the projects.

Silverlight itself is deprecated, and version 4.0 is not supported at all on Windows 8 or later.

### CODE REVIEW

**Comment by jonorossi** [comment]
@jamesathey thanks for the PR, however I'm not going to merge this as it will cause conflicts for the .NET Core work that is underway on the netcore branch. We decided (#100) back in July that we are dropping support for both Silverlight 4 and 5 for Castle Core v4.

**Comment by jamesathey** [comment]
@jonorossi Should I start sending PRs to get Xamarin.Android builds working
with the netcore branch then?

**Comment by jonorossi** [comment]
Feel free to work off that branch, but I won't be merging anything that isn't .NET Core work into that branch. The community especially including Microsoft employees are pushing hard to have .NET Core support so that branch should be back in master within the next few weeks.

**Comment by jamesathey** [comment]
That's fine; if that branch is really merging in soon, then it makes much
more sense for me to base my work on that.

**Comment by jamesathey** [comment]
@jonorossi Any news on when you'll start accepting PRs into master again? I can't get moq4 to merge my Xamarin.Android branch without the corresponding support in Castle, and this PR is the first step towards that.

**Comment by jonorossi** [comment]
@jamesathey sorry for the delay. I'm going to close this PR for now as the code underneath has changed so much in the .NET Core branch, and leave removing Silverlight 4.0 and 5.0 to #100.

Please see #135 which I just created about how to get Xamarin.Android support actually happening.

**Pull request closed without merging**
