### PR TITLE
.NET Core support for Castle.Core

### PR DESCRIPTION
**Pull request by MattGal**
## Port Castle.Core to .NET Core profile

* Previously raised and known issues have been addressed
*  (Outdated) Xunit tests are passing with some disabled :
	* Tests which used Assembly path-based loading APIs are disabled as this is not explicitly provided in .NET Core (Can be achieved via dependency injection in ASP.NET 5-hosted apps but it doesn't seem appropriate to depend on this.  Please comment if not, as I can provide implement it taking a dependency on ASP.NET 5 interfaces.
	* Five DictionaryAdapterFactory tests have been marked as Skip:
		* Two depend on ICustomAttributeInfo interface that has been removed in the Core profile.  I continue to investigate ways to make this work.
		* Three are failing because code like this correctly applies the prefix attribute, but fails to correctly add it to the IDictionary accessor.

##  
			var person = factory.GetAdapter<IPersonWithPrefix>(dictionary);

			person.Name = "Craig";

			Assert.Equal("Craig", dictionary["Name"]);

* Commits have been squashed and are currently mergable with no conflicts
* Aside from the DictionaryAdapterFactory issues I am done with associated work and awaiting for guidance on how to move forward
* I am available post-merge to assist with any follow-up needs including coordinating with teams at MS, fixing issues, etcetera, for as long as this is needed.  Please make sure to include **@mattgal** on posts so I get alerted.

Thanks everyone for your patience, I'm eager to get this right and merged.

(Edited from previous WIP state)

### CODE REVIEW

**Comment by MattGal** [comment]
Hi,
     The Add-NetCore-Beta5 Branch now has no test project.  I left the test project as a branch in case it's wanted as a template for what test projects currently look like in .NET Core projects (branch is CoreTests).  This can be picked back up when NUnit is available for CoreCLR.

Thanks,
Matt

**Comment by uhaciogullari** [comment]
I think you had a problem with line endings.

**Comment by MattGal** [comment]
Thanks @uhaciogullari Did a bunch of manual squashing and cleanup, which should have addressed this and also rebased on top of the most recent upstream changes.

**Comment by kkozmic** [comment]
Nice starting point @mattgal thanks for taking that on.

It looks like there is some issue with code indention that makes out quote hard to read through the changes and have a meaningful conversation about them.

**Comment by floydpink** [comment]
Adding `?w=1` as mentioned under the `Whitespace` section [here](https://github.com/blog/967-github-secrets) would allow reading through all that indentation noise, @kkozmic - https://github.com/castleproject/Core/pull/92/files?w=1

But I agree that getting the same indentation settings into the editor would be a great idea.

On that note, the [`.editorconfig`](https://github.com/castleproject/Core/blob/master/.editorconfig) probably could be [beefed up a little more](http://editorconfig.org/#example-file) to enforce some more of the project coding-style.

Great work, @MattGal ! :clap:

**Comment by kkozmic** [comment]
Sounds like a pull request Hari 😉 (editorconfig)

**Comment by MattGal** [comment]
Hi all,
   Being new to GIT after spending many years in TFS and proprietary MS source control I may have made some mistakes, but I also have strong feelings about Tabs.  After fixing up the whitespace issues from before (I somehow got my whitespace such that I couldn't interactively rebase a linear series of commits.  Huh?)   I checked everything and the only issue I noted was a place where VS' "Format Document"  had replaced some tabs with sets of 4 spaces in one file, and I approve of that sort of change since tabs look different in all sorts of editors.

However, if there's something else I need to do to fix up indentation, do let me know and I'll update the PR.

**Comment by floydpink** [comment]
@kkozmic - I shall try and get a PR in with an updated `.editorconfig`

@MattGal - the project's [coding standards](https://github.com/castleproject/Home/blob/master/coding-standards.md) does suggest using only tabs and not spaces. It also talks about how ReSharper (if you use it) can be configured to use the Shared project settings.
Also, if you do not have it yet, do you want to try installing the [EditorConfig VS Plugin](https://visualstudiogallery.msdn.microsoft.com/c8bccfe2-650c-4b42-bc5c-845e21f96328) and see if that helps to enforce tabs?

**Comment by MattGal** [comment]
@floydpink  and @kkozmic , the Whitespace issues should be addressed.  I won't be able to work on this any more this week, but please consider merging it in.  Looks like someone has already made changes upstream that will need to be merged.

**Comment by jonorossi** [comment]
@MattGal that actually made it worse. Unfortunately we don't have a completely consistent repository and it looks like you've run a formatter over the whole thing which introduced heaps more whitespace changes. For now I'd just leave this PR as is with respect to my comments in #90.

**Comment by MattGal** [comment]
@jonorossi  I have now lovingly fixed up all my whitespace issues with the notable exclusion of DynamicProxy\Tokens\InvocationMethods.cs (it does not seem to follow a particular pattern) bringing the size of the change down quite a lot.  I've also modified it to use the final beta5 DNX as that is publicly available now.

I'd very much like to get this PR accepted at this point, and would greatly appreciate a chance to do so before any other large, conflicting one is merged in :)

**Comment by uhaciogullari** [comment]
@MattGal Just an idea: you can just exclude DictionaryAdapter folder in project.json so you wouldn't need to modify all those files.

**Comment by MattGal** [comment]
@uhaciogullari , I had thought of that, but there is a fair amount of functionality in the folder that does actually build and may end up being useful.  Also, the tax is paid now :)

**Comment by richlander** [comment]
Anything left for @MattGal to do to land the PR?

**Comment by jonorossi** [comment]
I don't want to sound rude or ungrateful for the effort but there is still quite a bit of work to do. We and our users expect the same sort of level quality as the .NET Framework does, i.e. this can't just be a fire and forget port to .NET Core. If we are changing code there needs to be a reason for it, and that needs to be documented so we can continue maintaining this code as we have been for well over a decade.

From a cursory look, things to do include:
* There are now quite a few added #ifdefs that have code in .NET Core but nothing in everything else (i.e. everything else won't compile)
* Fix the TODOs that refer to the fact that the correctness needs to be verified
* Fix or document why we need some of the changes which looks like the code now doesn't do what it does on all the other platforms. Some where I assume the API or overload may not be available in .NET Core that the code just ignores parameters, passes null, or doesn't do certain checks.
* Unit tests
* Determine whether `dnxcore50` is the right framework, should we be using `dotnet`?
* Consider using a symbol other than `CORECLR` for .NET Core because it really isn't specific to the `CORECLR`, if anything it would be `COREFX`, `DNX`, `NETCORE`, `...`.
* Look at what DNX generates as a NuGet package and how that compares to our build scripts' output, since I assume we'll be using that from now on

**Comment by MattGal** [comment]
Thanks for getting back to me @jonorossi.  I'll work on this if I get time. I have a few comments and questions about how you'd like things:

- Since I started doing this, it has become possible to build a more traditional portable class library project targeting DNX Core profiles.  I'll likely redo the project this way so that build is nicer looking, but it would mean (just like it does with Xproj) that this library could only build from VS 2015.  Is that OK?

- What do you mean by "i.e. everything else won't compile"?  At least on my setup, I can build all the other flavors with the changes made via the build scripts provided

- I picked CORECLR as the tag because it has had many, many names and this was the original.  DNX isn't right because that's the name of the host, not the framework.  Can you pick a symbol you want?

- Regarding unit tests: this brings us back to the previous issue, specifically that NUnit doesn't have .NET Core Support yet.  Unit tests that existed were jure removed. What would you recommend?  Further, to work on core, the tests as-is would need some amount of #ifdefs to work.  is that reasonable?

Thanks for your patience, this is one of my first experiences trying to contribute to OSS.

**Comment by MattGal** [comment]
Hi @jonorossi , some updates: 
- CoreCLR is NETCORE everywhere now.  

- The project is now a new-style Portable Class library, so will require VS 2015 + Windows SDK for it to build correctly.  This makes integrating it into the existing NuPkg easier.

- You were correct that there were some bad auto-merges hidden in the codebase.  All fixed, now has identical pass rates for all non-.NET Core branches as before.

- Added back Unit test Xunit project (just to have something to test with, not trying to make anyone convert...)   Currently there are 8 remaining failures, all in DictionaryAdapterFactoryTestCase... it's fairly gnarly to debug, I would love help on this.

- Took a stab at updating the NuSpec but I had to do stuff like manually substitute tokens and kick off builds to make a usable package (happy to share this if anyone wants to try it in their DNX project) 

- Various formatting and other fixups.

Thanks everyone for your patience!

**Comment by MattGal** [comment]
@jonorossi , any update on this, or other things I can do to improve the PR?

**Comment by adamralph** [comment]
As can be seen from the issue links, the three major OSS .NET mocking frameworks (Moq, NSubstitute and FakeItEasy) are all under pressure from the community to provide support for .NET core so there is a lot of interest in getting this in. All efforts are hugely appreciated.

**Comment by AmadeusW** [comment]
I'd like to help getting this done. What's left to be done from @jonorossi previous comment? And how is this PR related to the `netcore` branch?

**Comment by jchannon** [comment]
What's the status of this? We want to get Nancy on CoreCLR which depends on FakeItEasy which depends on this :smile:

**Comment by thecodejunkie** [comment]
I'll +1 this. Like @adamralph said, it's a core (no pun intended) component for the major mocking frameworks used by .NET OSS projects

**Comment by adamralph** [comment]
So what's the status? Has this been done elsewhere?

**Comment by jonorossi** [comment]
See the linked issue, #90.

**Pull request closed without merging**
