### PR TITLE
Optimize `TypeUtil.Sort`

### LINKED ISSUE #386: GC problem on Proxy Creation
I get performance issue in a programm using Proxy generation. I use perfview fo diagnostic and find out that proxy creation involve many GC string allocationns wich result in too many garbage collections.

gc_castle

So reason is TypeUtil.Sort which uses "AssemblyQualifiedName" which do a string.concat. 
Why there is a need to sort interfaces? And is there a way to to this without AssemblyQualifiedName?

### PR DESCRIPTION
**Pull request by stakx**
This resolves #386 through a few (admittely micro-) optimizations:

* Avoids comparing by `Type.AssemblyQualifiedName`, which performs hidden string concatenation & allocation. A quick benchmark suggests that comparing `Type.FullName` and `Type.Assembly.FullName` separately is about twice as fast.

* Using an `IComparer<Type>` instead of a `Comparison<Type>` delegate avoids unnecessary double dispatch (caused by the latter being wrapped as an `IComparer<Type>` inside the framework).

* Comparing case-sensitively instead of case-insensitively seems more appropriate for .NET type names, and should be faster.

(This might seem like too much additional code for too little gain, but consider that the C# compiler generates about the same amount of hidden code for a lambda.)

### CODE REVIEW

**Comment by jonorossi** [comment]
@stakx looks good, I don't think it is too much code for the performance gain/GC impact. The only thing I think would be good is to add a comment about why it exists so someone doesn't try reverting the change in the future to simplify code.

**Comment by stakx** [comment]
@jonorossi - Good point. Done!

**Comment by jonorossi** [comment]
@stakx is it worth updating the changelog?

**Comment by stakx** [comment]
@jonorossi, I don't think so, there will likely be no noticeable difference in behavior or speed.

**Pull request merged**
