### PR TITLE
fixed minor typos

### PR DESCRIPTION
**Pull request by hamidzr**

### CODE REVIEW

**Comment by fir3pho3nixx** [comment]
Is it mega cheeky of me to ask we fix ALL the typo's?

**Comment by hamidzr** [comment]
sure thing do you see any more typos?

**Comment by stakx** [comment]
I quickly ran [Visual Studio Spell Checker](https://ewsoftware.github.io/VSSpellChecker), there isn't a lot that needs fixing:

* Some `dont` and `doesnt` (without apostrophe) in the unit test project
* `acceptible` instead of `acceptable` also in the test project
* `specied` instead of `specified` in `ExtendedNLogLogger.cs` in the NLog integration project

That's about it. But perhaps run a spellchecker too, I haven't taken an overly close look.

**Comment by stakx** [comment]
> btw my editor also caught a bunch of extra white spaces at the end of the lines which could be cleaned easily.

@hamidzr - Others may see this differently, but I think trailing whitespace should not be cleaned up systematically for its own sake. For example, it negatively affects working with `git blame` by introducing lots of changes that don't mean anything. My personal policy on this is: If you're editing a line of code anyway and it happens to have trailing whitespace, then by all means remove it; otherwise, don't. (Same goes for missing end-of-line terminators at the end of files: If you edit the last line, and there's no line terminator, then add it; otherwise, don't.)

**Comment by fir3pho3nixx** [comment]
Please don't worry about white space. I set a PR on fire in Castle Windsor messing with this. I am definitely with @stakx on this. :)

**Comment by hamidzr** [comment]
That's fair :)

**Comment by jonorossi** [comment]
@hamidzr looks great, merged.

**Pull request merged**
