### PR TITLE
Fix Mono build by excluding failing modopt tests

### PR DESCRIPTION
**Pull request by stakx**
as discussed in https://github.com/castleproject/Core/issues/277#issuecomment-312653793. I am happy to provide a proper fix for Mono at a later time, but I guess for now it's more important to have a successful build again.

### CODE REVIEW

**Comment by jonorossi** [comment]
@stakx could you change the library code to use Array.Reverse rather than Linq.

**Comment by jonorossi** [comment]
@stakx could you also update the entry in the changelog to mention this does not work on Mono, doesn't need to say why or anything just those 5 words.

**Comment by stakx** [comment]
@jonorossi - yep, will do. I wanted to see first whether the build works allright. I'll add a commit.

**Comment by stakx** [comment]
> could you change the library code to use Array.Reverse rather than Linq.

Sorry, overlooked that one. Will do that, too.

**Comment by jonorossi** [comment]
Thanks

**Pull request merged**
